#version: '3.9'

services:
  
  appi:
    
    ports:
      - ${APP_PORT}:3001
    
    container_name: aws_api
    environment:
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB_DATABASE=${DB_DATABASE}
          - DB_HOST=aws_psql
    
    
    build:
      context: .
      dockerfile: Dockerfile
 
